// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that generates a summary of a book based on its title and author.
 *
 * - generateBookSummary - A function that handles the book summary generation process.
 * - GenerateBookSummaryInput - The input type for the generateBookSummary function.
 * - GenerateBookSummaryOutput - The return type for the generateBookSummary function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateBookSummaryInputSchema = z.object({
  title: z.string().describe('The title of the book.'),
  author: z.string().describe('The author of the book.'),
});
export type GenerateBookSummaryInput = z.infer<typeof GenerateBookSummaryInputSchema>;

const GenerateBookSummaryOutputSchema = z.object({
  summary: z.string().describe('A short summary of the book.'),
});
export type GenerateBookSummaryOutput = z.infer<typeof GenerateBookSummaryOutputSchema>;

export async function generateBookSummary(input: GenerateBookSummaryInput): Promise<GenerateBookSummaryOutput> {
  return generateBookSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateBookSummaryPrompt',
  input: {
    schema: z.object({
      title: z.string().describe('The title of the book.'),
      author: z.string().describe('The author of the book.'),
    }),
  },
  output: {
    schema: z.object({
      summary: z.string().describe('A short summary of the book.'),
    }),
  },
  prompt: `You are a book summarization expert. Please provide a concise summary of the book based on the title and author provided.\n\nTitle: {{{title}}}\nAuthor: {{{author}}}\n\nSummary: `,
});

const generateBookSummaryFlow = ai.defineFlow<
  typeof GenerateBookSummaryInputSchema,
  typeof GenerateBookSummaryOutputSchema
>(
  {
    name: 'generateBookSummaryFlow',
    inputSchema: GenerateBookSummaryInputSchema,
    outputSchema: GenerateBookSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
